apiVersion: apps/v1
kind: Deployment
metadata:
  name: open_j00
  labels:
    app: open_j00
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: open_j00
  template:
    metadata:
      labels:
        app: open_j00
        tier: open_j00
    spec:
      containers:
        - name: open_j00
          image: daain/open_j00:${BUILD_ID}
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: open_j00
---
apiVersion: v1
kind: Service
metadata:
  name: open_j00
  labels:
    app: open_j00
spec:
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: open_j00
    tier: open_j00
  type: LoadBalancer
